### ISSUE TITLE
[Question] The Digital Clock in Calendars and Time Control Does not Work

### ISSUE THREAD

**Issue by acsinsurancegroup** [YetiForceCompany/YetiForceCRM#10520]
### Description

This probably should of been marked as a bug. However, I have already entered all of my system information several times previously and it's annoying having to post again every time.

I have a CentOS 7 Plesk Server with 7.2.18 PHP and no system warnings errors whatsoever on Yeti version 5.1 Stable complete.

The issue is that the Dial on the Clocks in the Calendars and Time Control modules do not work. I can click on the digital clock and click on a different time and select AM or PM and the only thing that ever changes is the AM or PM. The time stays as default no matter what I do. The only way for me to change the time is by clicking inside the time field and manually typing the time like 09:24 PM I use the 12 hour format if that matters.

Any suggestions?

**Comment by z0lo13** [comment]
wow i thought it was fixed in 5.1.0

i am unable update to 5.1.0 right due to custom modifications and 5.1.0 changed some structure.
@acsinsurancegroup did you check gitdeveloper?
https://github.com/YetiForceCompany/YetiForceCRM/issues/9727
https://github.com/YetiForceCompany/YetiForceCRM/issues/9659

**Comment by acsinsurancegroup** [comment]
@z0lo13 I know right. You would think such a simple and important thing like that would have been resolved by now. I get that they primarily use 24 hour time but not everybody does.

I had already seen the other two posts you referenced and still can't believe it hasn't been corrected. Funny you mention that about gitdeveloper. I just finished logging into it and the damn calendar there didn't even load up or work at all. See screenshot below. 

Personally, I wish no future versions would be released at all until absolutely everything has been fully tested and works 100% as it should prior to release. The updates are always scary and I tend to wait until I can test the updates in a test environment prior to updating my production instances.

![Screenshot from 2019-05-29 23-05-17](https://user-images.githubusercontent.com/42642523/58607983-31304480-8267-11e9-84fd-411a3fc225a2.png)

**Comment by z0lo13** [comment]
> 
> 
> @z0lo13 I know right. You would think such a simple and important thing like that would have been resolved by now. I get that they primarily use 24 hour time but not everybody does.
> 
> I had already seen the other two posts you referenced and still can't believe it hasn't been corrected. Funny you mention that about gitdeveloper. I just finished logging into it and the damn calendar there didn't even load up or work at all. See screenshot below.
> 
> Personally, I wish no future versions would be released at all until absolutely everything has been fully tested and works 100% as it should prior to release. The updates are always scary and I tend to wait until I can test the updates in a test environment prior to updating my production instances.
> 
> ![Screenshot from 2019-05-29 23-05-17](https://user-images.githubusercontent.com/42642523/58607983-31304480-8267-11e9-84fd-411a3fc225a2.png)

absolutely agree in Country i am using this crm There is No 24 hours format at all. All updated just bring more bugs almost no new features.

**Comment by paula-w** [comment]
Can you check gitdeveloper once again and let us know if the problem still exists in your opinion? If it does, please provide a detailed description of the problem.

**Comment by acsinsurancegroup** [comment]
@paula-w Yes I checked it and still has issue. The problem is you guys don't notice it because you all use 24 hour time. In my country we use 12 hour time and primarily MM/DD/YYYY format. So when I changed my preferences in the Gitdeveloper version to meet 12 hour time and calendar format, it at least changed the time which my system won't even do that. However, the calculated time stayed the same at 0.25 even though I entered a record with 4 hour difference. 

So, we just need the Time Control digital clock to accurately change time and that time be calculated using the 12 hour clock and calendar system I described above. I tweaked my calendar file that @mariuszkrzaczkowski referenced above and still doesn't work in my production system.

**Comment by mariuszkrzaczkowski** [comment]
If you want to help us fix bugs then please describe the problem more precisely and provide details on how to trigger it because your description is too general and we don't know how to trigger the bug.
Probably, there are more changes that need to be uploaded to fix the 12h format, we encourage you to test on gitdev and soon we will release a new version.

**Comment by z0lo13** [comment]
@acsinsurancegroup it is actualoly working on gitdev fine 

@mariuszkrzaczkowski i guess so far you can close the issue, i was not able to replicate the bug
