### ISSUE TITLE
SMTP server configuration error

### ISSUE THREAD

**Issue by webrelab** [YetiForceCompany/YetiForceCRM#3521]
#### Issue

When I try to save the configuration SMTP server, I get an error that the letter can not be sent.
According to the logs, the sender's name - empty
In YF 3.1 & 3.0 this bug does not play

#### How to trigger the error

1. Install YF 3.2
2. Set  System – Configuration -> Helpdesk Email - my SMTP account noreply@informen.ru
3. Set Mail – SMTP Server  > Outgoing Server:
    ssl://smtp.yandex.ru:465
    noreply@informen.ru
    password
    noreply@informen.ru
    Requires authentication - Yes
4. Save
5. "Test mail status :  Mail could not be sent to the admin user. Please check the admin emailid/Server settings"

#### Debug

DEBUG Users - Inside the function getUserEmailId. --- user_name =
DEBUG Users - User id is empty. so return value is ""
INFO DB - Start query: select from_email_field from vtiger_systems where server_type=?
INFO DB - Query parameters: [email]
INFO DB - End query
DEBUG Users - Inside the function setMailerProperties
INFO DB - Start query: SELECT * FROM vtiger_organizationdetails WHERE organization_id=?
INFO DB - Query parameters: [1]
INFO DB - End query
DEBUG Users - Inside the function setMailServerProperties
INFO DB - Start query: select * from vtiger_systems where server_type=?
INFO DB - Query parameters: [email]
INFO DB - End query
DEBUG Users - Mail server name,username,password => ssl://smtp.yandex.ru:465,noreply@informen.ru,password
INFO DB - Start query: select first_name,last_name from vtiger_users where user_name=?
INFO DB - Query parameters: [Informen Support]
INFO DB - End query
DEBUG Users - Inside the functin setCCAddress
DEBUG Users - Inside the functin setCCAddress
INFO Users - Inside of Send Mail function.
ERROR Users - Error in Mail Sending: **The following From address failed:  :** MAIL not accepted from server,553,5.7.1 Sender address rejected: not owned by auth user.

#### Your Environment

* YetiForce Version used: 3.2 (stable or master)
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by webrelab** [comment]
In dev version settings do not are saved

**Comment by konadrian** [comment]
I fixed saving form by this 796d9fe00fe2f95953ecd7b8244c084683bacba6. 
For the first problem did you change https://gitdeveloper.yetiforce.com/index.php?module=OSSMail&parent=Settings&view=index&block=8&fieldid=94 this values.
Do you have enable php_openssl on your server?

**Comment by webrelab** [comment]
My phpinfo on screenshot

![openssl](https://cloud.githubusercontent.com/assets/9144386/18429713/84afc1ba-7907-11e6-8ef8-076a97af37de.png)

**Comment by PercyP** [comment]
@webrelab 

I had this problem and my fix was for the outgoing server to be set as follows:
imap.yourwebsite.com
myemail@yourwebsite.com
Password
Tick yest for requires athentification

Next, I made sure the admin user email was the same as the outgoing server details. 

In Roundcube:

ssl://imap.yoursite.com
Port: 143
smtp.yoursite.com
smtp port - 25

Also, check the Logs/Server Configuration/Rondcube - I had to manually install the following
OK - PEAR
OK - Net_SMTP
OK - Mail_mime

Also check you have the correct php settings in the server tab

**Comment by webrelab** [comment]
@PercyP 

When you try to connect on IMAP, the application hangs up. In logs - "Inside of Send Mail function".
I think that it's not in the protocol - application is not setting address of outgoing mail in the test message, because it contains a bug

**Comment by webrelab** [comment]
In DEV version YF problem is not solved.
In logs: ERROR Users - Error in Mail Sending: The following **From address failed:  :** MAIL not accepted from server,553,5.7.1 Sender address rejected: not owned by auth user.
