### ISSUE TITLE
Access denied when access My mailbox

### ISSUE THREAD

**Issue by forreggbor** [YetiForceCompany/YetiForceCRM#3788]
#### Issue
Cant access to mailbox. Can't create mailbox. 
The settings in MAIL SMTP server are correct.
There is no log file created in any yetiforce folder on the server.

#### Actual Behavior
System settings -> Mail tools -> Mail scanner
Click on My mailbox button --> result: Acces denied!

#### Expected Behavior
Create mailbox and access to mailbox then able to setup mail scanner

#### How to trigger the error
System settings -> Mail tools -> Mail scanner
Click on My mailbox button --> result: Acces denied!

#### Your Environment
* YetiForce Version used: 3.4.0
* Browser name and version: latest version of Chrome, Firefox
* Operating System and version: Xubuntu 16.04

**Comment by skramanzia** [comment]
Please update to Hotfix 1, this hotfix resolved a lot of issue with OSSMAIL https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x/3.4x/hotfix-1/zip

**Comment by forreggbor** [comment]
The situation is better. Now I don't get Access denied but 500 internal server error instead.

**Comment by forreggbor** [comment]
Here is the php log:
[25-Nov-2016 13:03:41 America/Chicago] PHP Deprecated:  Non-static method OSSMail_Record_Model::GetSite_URL() should not be called statically, assuming $this from incompatible context in /home/xxxx/public_html/ugyfelszolgalat/ugyfelkezeles/modules/OSSMail/views/index.php on line 20

[25-Nov-2016 13:03:41 America/Chicago] PHP Notice:  Undefined variable: log in /home/xxxx/public_html/ugyfelszolgalat/ugyfelkezeles/include/Webservices/Utils.php on line 441

[25-Nov-2016 13:03:41 America/Chicago] PHP Notice:  Undefined index: LBL_CUSTOM_INFORMATION in /home/xxxx/public_html/ugyfelszolgalat/ugyfelkezeles/modules/CustomView/CustomView.php on line 1388

[25-Nov-2016 13:03:41 America/Chicago] PHP Notice:  Undefined index: LBL_DESCRIPTION_INFORMATION in /home/xxxx/public_html/ugyfelszolgalat/ugyfelkezeles/modules/CustomView/CustomView.php on line 1388

[25-Nov-2016 13:03:41 America/Chicago] PHP Notice:  Undefined variable: log in /home/xxxx/public_html/ugyfelszolgalat/ugyfelkezeles/include/Webservices/Utils.php on line 441

**Comment by skramanzia** [comment]
Check This

https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html

**Comment by forreggbor** [comment]
I configured everything according the requirements. Still 500 internal error. I attached the log file.
In the RoundCube engine server config I see these errors:
ERROR - SQLite (v2) | | http://www.php.net/manual/en/ref.pdo-sqlite.php
ERROR - SQL Server (SQLSRV) | | http://www.php.net/manual/en/ref.pdo-sqlsrv.php

ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime

ERROR - suhosin.session.encrypt| is '1', should be '0'
BTW If I set 'suhosin.session.encrypt' to 0 then Yeti ask me to login before every action/click! I click on anything I get the login screen and if I do the authentication then I see the result. I have to do it after every click.

[log.TXT.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/614086/log.TXT.zip)

**Comment by forreggbor** [comment]
Here is the apache server log entries when I open the My Mailbox.

Although I see 500 internal error in Yeti I don't find it in apache log but there is a 404 error.

[apache_log.txt.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/614109/apache_log.txt.zip)

**Comment by forreggbor** [comment]
OK. I'm much closer. The permission of some files was not 644. I fixed it and the 500 internal error gone.
Now there is an other issue came up when I click My mailbox.

ERROR: Wrong 'suhosin.session.encrypt' option value and it wasn't possible to set it to required value (). Check your PHP configuration (including php_admin_flag).

I opened roundcube directly with http and I see the login screen.
If I open roundcube with https I get the above error.

I added a php.ini file to the roundcube directory containing suhosin.session.encrypt=Off. If I run phpinfo() in roundcube dir it says that it's Off.

Any idea?

**Comment by skramanzia** [comment]
This is just a guess but are you sure you changed the correct php.ini file and have you restarted the webserver since (to load the new config)?

**Comment by forreggbor** [comment]
I realized that if I download and install the roundcube using module manager the file permissions are wrong and that cause the 500 Internal error message.
I have had to change the file permissions to 644 manually and it solves the problem. Maybe it's a bug.

**Comment by mgiammarco** [comment]
I have the same problem. I have checked permissions and also installed update. But the problem persists. Can you help me in debugging?
